name: shiori_flutter
description: "Shiori project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: 3.8.1
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  envied: ^1.0.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  go_router: ^14.6.2
  hugeicons: ^0.0.7
  json_annotation: ^4.9.0
  ming_cute_icons: ^0.0.7
  package_info_plus: ^8.0.0
  permission_handler: ^11.4.0
  riverpod_annotation: ^2.6.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  custom_lint: ^0.7.0
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.2
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
flutter:
  uses-material-design: true
